server:
  ingress:
    enabled: true
    hosts:
      - $ARGOCD_HOST
    tls:
      - secretName: argocd-server-tls
        hosts:
          - $ARGOCD_HOST
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

configs:
  $ARGOCD_ADMIN_PASSWORD
  $GITOPS_REPO_URL

certificate:
  enabled: true
  domain: $ARGOCD_HOST
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-prod
